all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
all_joints_names:
- nose
- forefoot_right_toe
- forefoot_right_groin
- forefoot_left_toe
- forefoot_left_groin
- hindfoot_right_toe
- hindfoot_right_groin
- hindfoot_left_toe
- hindfoot_left_groin
- tail_root
- tail_end
batch_size: 1
bottomheight: 400
crop: true
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_task1Apr1\task1_name195shuffle1.mat
dataset_type: default
display_iters: 1000
global_scale: 0.8
init_weights: C:\Users\taket\Anaconda3\envs\pydlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_task1Apr1\Documentation_data-task1_95shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 11
pos_dist_thresh: 17
project_path: C:\Users\taket\task1-name1-2020-04-01
rightwidth: 400
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
